import type { OrderItem } from "./types";

export const INITIAL_SEED_ORDERS: OrderItem[] = [
  {
    id: "ord-1",
    orderNumber: "SQ-892411",
    customerName: "زين مطيع",
    customerPhone: "773209744",
    customerCity: "صنعاء",
    productTitle: "حذاء رياضي أصلي - مقاس 42",
    storeName: "SHEIN",
    status: "new",
    originalPrice: 158,
    intlTrackingNumber: "SQ-892411",
    createdAt: new Date().toISOString(),
  },
  {
    id: "ord-2",
    orderNumber: "SQ-892412",
    customerName: "محمد غالب الحاشدي",
    customerPhone: "771234567",
    customerCity: "عدن",
    productTitle: "حقيبة نسائية كلاسيكية جلد فاخر",
    storeName: "TEMU",
    status: "shipped",
    originalPrice: 220,
    intlTrackingNumber: "SQ-892412",
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: "ord-3",
    orderNumber: "SQ-892413",
    customerName: "أحمد بن عبد الله",
    customerPhone: "772223344",
    customerCity: "تعز",
    productTitle: "سماعات بلوتوث عازلة للضوضاء برو",
    storeName: "Amazon",
    status: "delivered",
    originalPrice: 310,
    intlTrackingNumber: "SQ-892413",
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
  },
  {
    id: "ord-4",
    orderNumber: "SQ-892414",
    customerName: "سارة عبد الرحمن",
    customerPhone: "778899001",
    customerCity: "حضرموت",
    productTitle: "فستان سهرة أنيق تركي",
    storeName: "Trendyol",
    status: "new",
    originalPrice: 195,
    intlTrackingNumber: "SQ-892414",
    createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
];
